### ISSUE TITLE
Responsible for Testing

### ISSUE THREAD

**Issue by taranjitsinghboparai** [taranjitsinghboparai/COMP313-002-Team4#10]

**Comment by hlac** [comment]
Instead of assigning a dedicated person to perform testing, you'll notice that each source file that you work on is based off of an issue (e.g. task equivalent to an issue).  So when you commit your source, make sure you include in the commit message the integer identifier for the given issue.  This will generate a link in your issue leading back to the code.  So when you perform testing, you can close it with a closing keyword in your commit message.

**Comment by hlac** [comment]
Testing is associated with specific production code and each test could be
a separate issue.


Best Regards,
Hao C. Lac, Ph.D. (Computational Science)
