### ISSUE TITLE
Responsible for Website Development and Hosting

### ISSUE THREAD

**Issue by taranjitsinghboparai** [taranjitsinghboparai/COMP313-002-Team4#8]

**Comment by hlac** [comment]
Try phrasing your Github issues as an actionable item instead of implying a
responsibility (that's what the assignee capability is used for anyway).
For example, a possible issue is "Investigate options for hosting, verify
feasibility with simple test app, and document".


Best Regards,
Hao C. Lac, Ph.D. (Computational Science)
